IDCHAIN_RPC_URL = 'https://idchain.one/rpc/'
SEALING_BORDER = 5
DEADLOCK_BORDER = 15
RELAYER_BALANCE_BORDER = 1
RELAYER_ETH_ADDRESS = '0x0df7eDDd60D613362ca2b44659F56fEbafFA9bFB'
DISTRIBUTION_BALANCE_BORDER = 500
DISTRIBUTION_ETH_ADDRESS = '0x6E39d7540c2ad4C18Eb29501183AFA79156e79aa'

CHECK_INTERVAL = 5
MAX_MSG_INTERVAL = 24 * 60 * 60
MIN_MSG_INTERVAL = 10 * 60

IDCHAIN_APP_URL = 'http://node.brightid.org/brightid/v6/apps/idchain'
FAUCET_SP_BALANCE_BORDER = 100

KEYBASE_BOT_KEY = 'PUT_YOUR_KEY_HERE'
KEYBASE_BOT_USERNAME = 'idchain_bot'
KEYBASE_BOT_CHANNEL = {'name': 'idchain', 'topic_name': 'alerts', 'members_type': 'team'}

TELEGRAM_BOT_KEY = 'PUT_YOUR_KEY_HERE'
TELEGRAM_BOT_CHANNEL = '@idchain_alerts'