IDCHAIN_RPC_URL = 'https://idchain.one/rpc/'
SEALING_BORDER = 5
DEADLOCK_BORDER = 15
BALANCE_BORDER = 1
RELAYER_ETH_ADDRESS = '0x0df7eDDd60D613362ca2b44659F56fEbafFA9bFB'

SENT_TIMEOUT = 60 * 60
CHECK_INTERVAL = 5

KEYBASE_BOT_KEY = 'PUT_YOUR_KEY_HERE'
KEYBASE_BOT_USERNAME = 'idchain_bot'
KEYBASE_BOT_CHANNEL = {'name': 'idchain', 'topic_name': 'alerts','members_type': 'team'}

TELEGRAM_BOT_KEY = 'PUT_YOUR_KEY_HERE'
TELEGRAM_BOT_CHANNEL = '@idchain_alerts'