services:
  redis_custom:
    image: redis:latest
    container_name: redis_custom
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "300", "1", "--appendonly", "no"]

  monitor_service:
    build: ./monitor_service
    volumes:
      - ./monitor_service:/app
    env_file:
      - config.env
    depends_on:
      - redis_custom
    restart: unless-stopped

  alert_service:
    build: ./alert_service
    volumes:
      - ./alert_service:/app
    env_file:
      - config.env
    depends_on:
      - redis_custom
      - monitor_service
    restart: unless-stopped

  watchdog:
    build: ./watchdog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - config.env
    restart: always
    depends_on:
      - redis_custom
      - alert_service
      - monitor_service

volumes:
  redis_data:
    driver: local
