import os

HTTPS_RPC_URLS = os.environ["HTTPS_RPC_URLS"].split(",")
WSS_RPC_URLS = os.environ["WSS_RPC_URLS"].split(",")
SEALING_BORDER = int(os.environ["SEALING_BORDER"])
DEADLOCK_BORDER = int(os.environ["DEADLOCK_BORDER"])
RELAYER_BALANCE_BORDER = int(os.environ["RELAYER_BALANCE_BORDER"])
RELAYER_ADDRESS = os.environ["RELAYER_ADDRESS"]
DISTRIBUTION_BALANCE_BORDER = int(os.environ["DISTRIBUTION_BALANCE_BORDER"])
DISTRIBUTION_ADDRESS = os.environ["DISTRIBUTION_ADDRESS"]
IDCHAIN_EXPLORER_URL = os.environ["IDCHAIN_EXPLORER_URL"]
IDCHAIN_ARAGON_URL = os.environ["IDCHAIN_ARAGON_URL"]
EIDI_CLAIM_URL = os.environ["EIDI_CLAIM_URL"]
EIDI_CLAIM_API = os.environ["EIDI_CLAIM_API"]
CHECK_INTERVAL = int(os.environ["CHECK_INTERVAL"])
REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = os.environ["REDIS_PORT"]
